name: Stage Build

on:
    workflow_call:
      secrets:
        DOCKERHUB_TOKEN:
          required: true    
        DOCKER_USERNAME:
          required: true    

env:
  REGISTRY: roxsross12
  REPOSITORY: ${{ github.event.repository.name }}

jobs:

  build_to_hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: |
          VERSION=`jq -r '.version' ./package.json`
          docker build -t $REGISTRY/$REPOSITORY:$VERSION .
          docker push $REGISTRY/$REPOSITORY:$VERSION